services:
  pgdatabase:
    image: postgres:13
    environment:      
      - POSTGRES_USER=root 
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi
      
    volumes:
      - ./docker/postgres-volume:/var/lib/postgresql/data:rw
      
    ports:
      - 5000:5432
      
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    
    volumes:
      - ./docker/pgadminvol:/var/lib/pgadmin:rw
    ports:
      - 8080:80 